### ISSUE TITLE
Sea-province rivers?

### ISSUE THREAD

**Issue by Helliaca** [Helliaca/HoI4-LotrMod#13]
If you've ever played [Old World Blues](https://steamcommunity.com/sharedfiles/filedetails/?id=2265420196), you may have noticed that some of the thicker rivers are made by using sea-provinces (ocean) and stretching them out into the shape of rivers. This is what it looks like:

![image](https://user-images.githubusercontent.com/18307020/115976193-b7e11f80-a56b-11eb-91dd-115e9dca1ebb.png)

This naturally makes crossing the river a lot more difficult, as you can *only* cross it through straits or naval invasions.
I can see this bringing the mod some benefits in certain areas:
- Navy would become far more relevant, as naval control over rivers allows one to stage naval invasions etc. (Think of the Black Ships from Harad invading Minas Tirith by sailing along the river with their ships).
- Osgiliath could be made into the strategically important crossing point it is supposed to be. Some other locations like Bree can also be made more strategically important.

Potential drawbacks:
- The endeavour it would take to implement
- This would obviously upset the balance significantly. Holding as Gondor vs Mordor becomes a whole lot easier when you only need to hold Osgiliath + a few other crossing points.
- In HoI4 sea provinces can't belong to nation, thus (in the case of just Osgiliath) there would be a long strip of not-Gondor going right through Gondor. This might also lead to the "Gondor"-text showing up weirdly, as it tries to adapt itself around the sea provinces. This doesn't seem to be too much of a problem in OWB:

![image](https://user-images.githubusercontent.com/18307020/115976321-18249100-a56d-11eb-82e3-2e5aa53d30ef.png)

But it might look worse in our case.

Thoughts?

**Comment by Ryless** [comment]
I actually had similar thoughts last time I played OWB since the river Anduin is impassable in this mod, and I thought something like this would be a potential solution to that. I forgot about it since I didn't want to mess with the map. I think it is a pretty good idea. Mainly for the point of making Osgiliath as important as it is supposed to be. The Anduin is extremely important lore-wise to the whole of middle earth so I'm all for it. Lore wise it would make a lot of situations make more sense and it should make gameplay more interesting so I think it definitely fits.

As for the country name problem, I don't think it would cause issues since it doesn't in OWB. Maybe they have done something to make sure it doesn't? I'm trying to think what a countries name looks like with multiples continents in vanilla but I can't picture it.

If you are down for the work I'd say go for it, maybe with your "hokus pokus" shenanigans it'll go smoothly.

**Comment by Helliaca** [comment]
Here's an example of what happens with Gondot when the Anduin river cuts through it:

![image](https://user-images.githubusercontent.com/18307020/115994578-f01e4780-a5d7-11eb-8399-a1c523aa42b0.png)

**Comment by Helliaca** [comment]
Nvm, I found a solution: Leaving a little land-bridge between the two sections (at Osgiliath for instance). I believe this is what OWB does. Looks like this:
![image](https://user-images.githubusercontent.com/18307020/115995465-96b81780-a5db-11eb-941b-65714f98e755.png)

The problem that comes from this is, that everything north of Osgiliath will be cut off from the south. I will look into putting in canals (like Suez or Panama in vanilla hoi4) at these land-crossings.

**Comment by Ryless** [comment]
> everything north of Osgiliath will be cut off from the south.

What do you mean by this exactly? 

I think it looks pretty good with the river.

**Comment by Helliaca** [comment]
> What do you mean by this exactly?

You won't be able to sail a ship upstream from Osgiliath, since there is a land connection that cuts it off. This can be solved by adding Panama-canal-type connections in those places though.

> I think it looks pretty good with the river. What don't you like about it?

I think the border is too pronounced, as though the river is not part of the country. There are also some further visual issues with this. Namely it is near-impossible to correctly see the green/red/yellow color of naval superiority.

There is a functional prototype on the [river-remake](https://github.com/Helliaca/HoI4-LotrMod/tree/river-remake) branch if you want to check it out. Only things that are really left to do would be
- Add straits and canals to make the rivers fully navigable
- Remove the existing rivers that lie on top of the new sea-provinces.
- Since the previous thick rivers have been replaced with sea tiles, the remaining rivers ought to be thicker/bigger.

Even so, there are still more problems (like the aforementioned naval supremacy color, lack of naval bases along the rivers, some ships sailing on land occasionally and the fact the cheesing the AI would be that much easier).
All in all, I find this to be too much trouble to be worth it. I'm going to leave it be, at least for now.

**Comment by Ryless** [comment]
Why don't you use adjacencies to make land bridges instead of actual land connections? As far as I know that is how OWB actually does it? That would potentially fix the issues with blocking the regions off and would look better but Idk if it would fix any other issues.
![Hearts of Iron IV Screenshot 2021 04 26 - 14 10 47 83](https://user-images.githubusercontent.com/80797099/116137512-43a49a00-a699-11eb-8d1b-000dbd474ac8.png)
See the red dots? that's a land crossing over the river.

**Comment by Ryless** [comment]
Also, I think the Anduin would certainly be cool to have as a sea province river but I'm not sure about every river around the map.

**Comment by Helliaca** [comment]
Yeah, I am/was aware of adjacencies, I referred to them as "straits" in my comments. My "todo-list" included "adding straits", which is exactly what I meant by that.

The fact that regions are blocked off is not a problem at all. As I said, adding canals fixes this issue entirely. (Just like you can add adjacencies across a river, you can add an adjacency across a small strip of land.

My plan was to use both, since *only* using straits would make crossing the river even harder for the attacker. (Gondor could probably hold the entire army of Mordor with ~4 regular 20widith divisions if they only need to hold straits). Whilst also making the game trivial vs AI, as holding straits is not something they properly do.

Land connections would represent major bridges at cities etc, whilst straits would represent riverfords.

OWB does also (or at least did in the past - when I last played it) use land connections.

**Comment by Helliaca** [comment]
Also, in case you didn't know: you make adjacencies/straits impassable by placing ships in the sea province inbetween.
Imagine Mordor being unable to cross to Osgiliath because Gondor leaves a couple of destroyers in the river :D

This is a fairly little known mechanic, but it would be a perfectly viable strat to keep Mordor permanently at bay.

Here's an example:
![image](https://user-images.githubusercontent.com/18307020/116165498-4be1f100-a6fc-11eb-80dd-77d5f1fee0df.png)
The french troops CANNOT cross to Sicily (even though there are no divisions there) because Italy has 7 destroyers in the underlying sea province. Here's the Italy POV:
![image](https://user-images.githubusercontent.com/18307020/116165654-9c594e80-a6fc-11eb-8006-ab40a003527d.png)

**Comment by Ryless** [comment]
Ah, I see. Well, it seems like the base game makes adding this feature too complicated then. I did not know about that strait-navy interaction. I tend to not mess with navy stuff often during my games unless I have to. Maybe with updates from Paradox, this kind of river stuff will be better in the future, but since a lot of the issues arise from the AI itself, I find that pretty unlikely. Either way, it was an interesting idea to check out. 

Balance itself could be improved but it would probably be smart to hold off on adding something like this that would cause more balance issues. In this instance, the good parts of the addition could easily be outweighed by balance issues so I think your arguments make a lot of sense.
