### ISSUE TITLE
Removing the soviets and switzerland

### ISSUE THREAD

**Issue by Helliaca** [Helliaca/HoI4-LotrMod#4]
Possible options that might work:

- Setting all the states in the ocean to have no owner.
- Setting all the provinces as 'sea' provinces.
- Removing the provinces as a whole and putting regular naval tiles there. (This might break a bunch of other things)

NOTE: Switzerland currently triggers some important events (IIRC they decide if the ring get captured or not), so if they are removed these decisions need to be given to someone else (like the northern wastes) or changes as to not require an AI in the first place.

**Comment by Ryless** [comment]
I used a batch text editor to get rid of all the owner lines for the SOV states. Definitely looks better and only takes a minute to do. I left Switzerland alone because I couldn't find the references for whatever they do and didn't want to break anything.

This adds the following error once you start the game for every state in the following file:
[21:09:46][resistance.cpp:386]: set override garrison strength for state with invalid Data = 685
[21:09:46][resistance.cpp:98]: state 685: occupation is not initialized
Think this is only if you have the La Resistance DLC tho but I'm not sure.

[NoSovstates.zip](https://github.com/Helliaca/HoI4-LotrMod/files/6300746/NoSovstates.zip)
(Can only add 100 files at a time to a commit, which is annoying.)

I feel like this is a fine step and if the goal is to redo the map in the future then something like this is really simple for now. The only bad thing is the errors. I also got an error from the new generic focus tree about dockyards but I don't know if that was already happening or not. It's a simple one-line change though.

**Comment by Helliaca** [comment]
Sweet! I changed the fellowshipevents to the northern wastes (Nepal) instead of switzerland and removed them as well. For reference, some focuses (namely fs.1, fs.2, fs.3, fs.4 and fs.5) send Nepal an event where the nepalese AI decides what happens as the outcome. :D 
There might be a better way of doing this now, but when I first made the mod this was the only way of making random events with *weighted chances* that would adapt dynamically to the context. (For instance: chances of Boromir stealing the ring is higher if Legolas + Gimli are not there.)

> Can only add 100 files at a time to a commit, which is annoying.

That's odd. I could commit and push all changed files with no issues.

> The only bad thing is the errors.

I fixed an error with one of the generic naval_effort focus. All the garrison strength errors appear to have no impact on the game itself.

**Comment by Ryless** [comment]
Yeah you can use a random_list function now. Works pretty well. I could go about changing those events to that as well while I do the other ring stuff.

**Comment by Helliaca** [comment]
The `random_list` function has been around for a while, but I dont think you can dynamically adjust the probabilites on it.

If you look at the [`fs.1` event](https://github.com/Helliaca/HoI4-LotrMod/blob/563b8cb4a5e1a7d136d7410b48f1f87f13edfb59/events/FellowShipEvents.txt#L21), for instance, you can see that the chances of isengard getting the ring change depending on the fellowship flags that are (`fs_gondor_1` would be faramir and `fs_gondor_2` would be boromir). Irrespective of that there is a static chance of 50% of boromir/faramir dying in the process. (With a `random_list`)

**Comment by Ryless** [comment]
You can put a modifier within the choice and use has_global_flag like this. This is from a Lothlorien tries to steal ring event and this would be the option that you would pick if you want to steal the ring.

option = {name = lothlorien.4.a
			add_political_power = -100
			ai_chance = { base = 50}

			random_list = {
			80 = { 
				modifier = {
					add = 10
					has_global_flag = fs_gondor_1}
				modifier = {
					add = 10
					has_global_flag = fs_mirkwood_1
				}
				modifier = {
					add = 10
					has_global_flag = fs_erebor_1
				}
				modifier = {
					add = 30
					has_global_flag = fs_gondor_2
				}
				modifier = {
					add = 30
					has_global_flag = fs_mirkwood_2
				}
				modifier = {
					add = 30
					has_global_flag = fs_erebor_2
				}

				LIT = { country_event = { days = 1 id = fs.100 } }
				
			}
			20 = {
				modifier = {
					add = 20
					has_global_flag = aragorn_dead
				}
				news_event = { hours = 12 id = news.371 }
		set_global_flag = ring_found
		LIT = { add_ideas = one_true_ring }
		set_global_flag = lorien_has_ring
				
			}
			}
			}

So it's 80-20 chance originally but I've tested this in-game and the percentages do change so I believe it works in the way you want it to.

**Comment by Helliaca** [comment]
Ah, either that was not possible before or I was never aware of it. Either way, if it works like this it would be a far more elegant solution than  sending choice-events to Nepal :D
