### ISSUE TITLE
New Map

### ISSUE THREAD

**Issue by Ryless** [Helliaca/HoI4-LotrMod#5]
[LOTRNEWMAP.zip](https://github.com/Helliaca/HoI4-LotrMod/files/6319371/LOTRNEWMAP.zip)

Got the new map to load. Looks good.

**Comment by Helliaca** [comment]
Wow, awesome! I'll open up a new branch with the new map. 

Do you think its a big problem how closely the map wraps around itself? Specifically, the distance right here:
![image](https://user-images.githubusercontent.com/18307020/114907308-3aa30580-9e1b-11eb-9522-284b9657e1e6.png)
is quite narrow. What do you think about it?

Otherwise, there might be some small details that are a bit off, but I think we'd be ready to start filling in states.

I could work on that if you aren't doing that already. We naturally shouldn't work on the same thing side by side.

What are you currently working on?

**Comment by Helliaca** [comment]
Update: new map is now on branch [map-remake](https://github.com/Helliaca/HoI4-LotrMod/tree/map-remake)

**Comment by Ryless** [comment]
Yeah, that was the one thing I had a problem with. From a lore standpoint, those parts of the map shouldn't be able to interact at all so they should, at the very least, be blocked off regardless of distance. The actual distance itself isn't as big of an issue to me but if you did want to widen the space, I'd say taking away some of the area to the east of the eastlands would be good. Then it would make the most important part of the map feel bigger as well. I don't really want to mess with the new map right now so you are 100% good to work on it. I did just finish the event stuff I believe so I do need to find something else to do and I think I'll open an issue for an idea I have on it and see what you think.

**Comment by Ryless** [comment]
Oh I did a couple things hopefully I don't forget any.

- If there is an adjacency file make sure it is empty except the last line
- I had to replace all of the strategic region areas up to 41 even though they were already there (Mapgen gives you those files but they need to look like the ones I gave you)
- You need to have the id line in every strategic region file from 1-41 (I think this is the biggest issue)
- I deleted all the states but one and put all the provinces in one state (I don't think you actually need to do this but it simplified everything)
- Put all provinces (except ocean/sea) in that state
- Put that state in the test supply area
I think that's it.

**Comment by Helliaca** [comment]
Progress report:

I've worked some hokus pokus and combined the provinces from the old map and the new one together. This has the *massive* benefit, that all the states, and province ids from the old version remain the same. This allows me to just copy over the old mod files and (appart from a select few provinces) the thing just works out of the box. This is what it looks like:
![image](https://user-images.githubusercontent.com/18307020/115127953-d2028700-9fda-11eb-8ec0-ff3f601aa600.png)
Since I'm using the old provinces, it really doesn't look all that different. But just for the map to take up the whole screen, I think its worth it.

There are just a few smaller things left that need to be fixed (like rivers), but other than that its already fully functional.

**Comment by Ryless** [comment]
Wow, very nicely done. How did you manage to transfer the provinces and states so perfectly? Seems like you made the space between Lindon and the far east further, did you just take away space between the new and old parts?
I think it looks pretty great.

**Comment by Helliaca** [comment]
Its a bit cumbersome to explain exactly what I did step by step, but in short: I photoshopped the mainland of the old map on top of the new one, then used some c# scripts to fix the borders and definition.csv, while maintaining the province ids of the old map.

Either way, I would say its done. This is what it looks like:
![image](https://user-images.githubusercontent.com/18307020/115156740-1565ff80-a086-11eb-928b-4257a3989c31.png)

Apart from it being bigger, not much has changed. The only significant changes to the map itself are:

The swamp is swampier: 
![image](https://user-images.githubusercontent.com/18307020/115156782-434b4400-a086-11eb-9942-599cee0c48fc.png)

I've added some impassable mountains around Helm's deep:
![image](https://user-images.githubusercontent.com/18307020/115156792-54945080-a086-11eb-98c0-f77da96bed51.png)

This should make Helms deep a more strategic strongpoint, as Isengard has to either cross a thick river or take Helms Deep to get to Edoras.

And lastly:

I've added a volcano at Mount Doom and turned Mordor's rivers into lava:

![image](https://user-images.githubusercontent.com/18307020/115156820-7f7ea480-a086-11eb-8d1f-bc6c8806d5c2.png)

 I've gone ahead and merged the whole branch into master, since for me everything appears to be working fine.
If the new map gives you trouble (doesnt work) let me know.

**Comment by Ryless** [comment]
I really like the helm's deep idea. It never really "felt" like helm's deep before and the mordor stuff is nice extra flair lol. I'll try it out tomorrow when I get time and let you know if I see anything weird.

**Comment by Ryless** [comment]
Tested it and it seems to work well for me as well.

**Comment by Ryless** [comment]
North Arthedain has some weird stuff going on in the water
![Hearts of Iron IV Screenshot 2021 04 19 - 11 33 43 83](https://user-images.githubusercontent.com/80797099/115271653-2acd3f00-a103-11eb-9733-c033524dd47d.png)

I also get this error:
[11:16:49][map.cpp:1207]: prov 15 has no continent
for all of the provinces. I think you assign those in definitions? but we really only need one continent for middle earth. I don't believe that it has an effect on the game really.

**Comment by Ryless** [comment]
Are you on Linux? The definitions file was saved in LF so it wasn't compatible with Windows. I switched it to CR LF for me and it works fine now.

**Comment by Helliaca** [comment]
No, I'm on a regular Win10. The script I wrote the definitions file with used "\n" (LF) for newlines, so that probably why it happened. Strange that I didn't have the same problem. But since its fixed now, I guess it doesn't matter either way 🤷
