### ISSUE TITLE
Resource Rework

### ISSUE THREAD

**Issue by Ryless** [Helliaca/HoI4-LotrMod#7]
The resources obviously don't make much sense for the most part so we should probably change them. Shouldn't be too difficult overall. I also made some of these decisions based on future ideas like replacing armor with horses/trolls/ents/mumakil and stuff like that. At least the names would change but they would act pretty similarly. Here are my thoughts on what to add. ( I picked six since that is how many are in the base game) I'd also have to edit the equipment requirements as well.

**Food (Oil)**
    Replaces Oil
    Every unit uses some food
    Tanks (aka horses/trolls/mumakil) use more infantry use a bit
    Every 100k of the population could use one as well?
    Can build farms that give you food? (new building, replaces oil refinery)

**Steel** 
     Nearly every equipment uses steel
     Otherwise the same as it is now
    Could build mines?

**Mithril**
     An extremely rare resource that allows the creation of very strong infantry troops
     Only place is from Moria? 
     Allows Moria to make a big difference after their war for whatever side wins
     Would take a moria change to the focus tree
     Would allow the building of extremely powerful infantry equipment
     Similar to Crystals in Equestria at War

**Lumber** 
     Used for weapons and catapults/trebuchets (Artillery)
     2 for pikes(Anti-tank 1 steel)
     1 for sword(2 steel)
     Can build logging camp?

**Horses** 
Used for cavalry (light/medium tanks)

**Flax**
Strings (Bows, Catapults)
Linen (Support equipment)

**Comment by Helliaca** [comment]
I'm not generally opposed to this idea, but keep the following in mind:

- Adding new resources and whatnot makes maintaining the mod through new patches more painful. I *highly* recommend not actually introducing new resources, but just reskinning the old ones and changing their localization. This should increase forward-compatibility with new patches and you won't have to change the GUI for trading windows etc.
- Dramatic changes to resources will have an impact on the games general balance. In my experience mods that change the resources a lot end up feeling unbalanced and unintuitive, with mechanics (like food) that end up more frustrating than fun.
- Introducing new units and equipment, especially based on custom resources, also requires changing the AI respectively. And even then, they will struggle to make good use of them.
- This also requires changing all the states and foci to the new resources in order for it to make sense.

I would suggest to keep things as simple and maintainable as possible. This is how I would go about it:

- *Steel*: Keep it as it is
- *Tungsten*: Change tungsten to flax/strings. Vanilla hoi4 artillery uses tungsten and imo should translate to bows and crossbows, not catapults/trebuchets (which are siege weapons and should give soft attack).
- *Chromium*: Swap out chromium for wood/lumber. Ships and heavy tanks require chromium eg wood. Would make sense to then swap the steel and chromium costs of all the ships. Heavy tanks would essentially work as catapults and super heavy tanks as trebuchets. (slow but high breakthrough and bonus against forts)
- *Rubber*: Swap out rubber for leather. The fact that refineries produce both oil and rubber would mean they would produce food and leather, which makes sense if its supposed to be farm. Support equipment should then cost rubber/leather instead of aluminium
- *Aluminium*: Not sure what to do with alu, but maybe you can replace it for Mithril. You'd obviously remove the alu cost of planes. 
- *Oil*: You could swap out oil for food, but food essentially comes from everywhere, and every unit needs food. I'm not a huge fan of the idea of having a food resource scattered all over the map (essentially in every state), so you should definitiely keep the food consumption on regular units very low, so that even states/countries with no food income can field decently sized armies. Also: you may wanna give the AI a buff to food-production, as the hoi4 AI already struggles really badly with fuel. I don't want to imagine how badly it does when *all* units consume it.

All in all, reworking the resources could be neat, but I suggest caution, planning and forethought. As I outlined above, its probably a good idea to not go all in with custom units/resources but to instead work towards that slowly by adapting the existing hoi4 mechanics step by step.

**Comment by Helliaca** [comment]
Essentially I'm suggesting that you don't create any new units/equipment for now, but just repurpose the existing ones:

- light tanks -> cavalry
- medium tanks -> heavy cavalry
- heavy tanks -> catapults
- super heavy tanks -> trebuchets
- artillery -> bows/crossbows

Then change reskin the resources:

- tungsten -> flax
- chromium -> lumber
- rubber -> leather
- aluminium -> mithril
- oil -> food

Then change the cost of some of the units

- support equipment -> rubber instead of alu
- planes -> rubber instead of alu
- all units -> add a small amount of fuel consumption

Then place the resources adequately throughout the map

This is, of course, just my thoughts/feedback. You don't have to stick 1:1 to this at all.

**Comment by Ryless** [comment]
I agree with pretty much everything you said and generally reskinning everything will be much easier so that was my plan already. One of the reasons I picked this as a project is that it is mostly visual and shouldn't be affected by switching to a new map so it won't be annoying to do. Also the food part I agree with but I would put the usage as low as possible and then see how it works. I imagine it will be fine because ultimately adding the lowest usage to every unit will do very little anyway, especially with the abundance of resources on the map, but it will make the resources make sense. It will be as similar as it could get to the normal oil use so it will only be as annoying as oil already is to the average player.

Basically, my process will be the following in order.

- Reskin the 6 resources in the game already (Eventually replace aluminum with mithril maybe, I like your leather addition)
- Update the equipment needs so they make more sense
-Change localisation so they make sense
^ This stuff is simple and won't require much balance ^ 
After that, I would consider the more in-depth stuff, but those kinds of additions aren't necessary so if they don't work, they don't work. (Buildings and more complicated stuff)




I was thinking more along these lines for the tech reskins tho.
But if you wanna go with your plan that's fine. Either way, replacing the icons and localisation for the resources would still have to happen the same way regardless and this would also be a tech rework even if it was just renaming. So in a way, this following part is a different project entirely.

- light tanks -> cavalry
- medium tanks -> heavy cavalry
- heavy tanks -> Trolls/Ents -> Only Entwood would get ents -> Only Mordor would get Trolls
- super heavy tanks -> Mumakill -> Only Harad would get this (Could send license to Mordor or whatever)
- artillery -> Catapults
- rocket artillery -> Trebuchet


I don't really know how bows and stuff would work here though. I guess they would be different infantry equipment but that could get complicated quickly.

**Comment by Helliaca** [comment]
I generally don't like turning vanilla hoi4 artillery (which does soft attack - damage vs infantry) into medieval siege weapons (which mostly just does damage vs buildings). I think archers fit much better here.
In addition, most hoi4 players *always* put artillery in their divisions, which makes more sense for archers than every division walking around with siege weapons.

Trolls/Ents/Mumakil fit heavy/super heavy tanks quite well. But since they are units that are limited to only certain nations (mordor, entwood etc), I would suggest turning these into custom units that are only available to that nation. (You would essentially copy the heavy tank units and changes their stats somewhat). I think locking out players out of heavy/super heavy tanks if they aren't playing ents/orcs limits the available options somewhat too much.

We could adapt the stats on heavy/super heavies to be more in line with catapults/trebuchets, but I still think they work for that, given that heavy tanks give breakthrough, hard attack and a damage bonus vs forts.

It does, however work like you described as well. I'll leave the decision up to you.

**Comment by Ryless** [comment]
Well, the only thing I will be doing with that stuff right now is assigning the resources to the equipment anyway so it isn't extremely important that we make the decision now. I agree with the locking-out players idea. I suppose we also have to figure out how planes would work too and so all of that can be done later in some sort of tech rework.

**Comment by Ryless** [comment]
![Hearts of Iron IV Screenshot 2021 04 15 - 17 23 22 68](https://user-images.githubusercontent.com/80797099/114945932-ddee1d80-9e0f-11eb-89e1-409d9ee86c5f.png)

How do you feel about these icons? Got them from https://www.pngrepo.com/ and edited them to make them work. No attributes or anything needed, free to use and edit.

**Comment by Helliaca** [comment]
To be 100% honest with you: I dont like them. I wouldn't be able to recognize the wheat and leather icons if I didn't know what they stood for. They also lack the black outline that the regular hoi4 icons have (look closely at the iron icon, its outlined in black).

I've searched around a little bit and found these for instance:
![icons](https://user-images.githubusercontent.com/18307020/114948480-604a0200-9e4f-11eb-9ee9-d6152c6f1abf.png)

I reckon at least the wood icon works well out of those, the food icon might look a little dodgy when its really small. 

Also, if we're going to change all the icons except steel, it might be a good idea to change steel aswell so it stays in line with the other ones.

**Comment by Helliaca** [comment]
Here are a couple more cc0 ones that could work:
![resource_pack_1](https://user-images.githubusercontent.com/18307020/114948739-e7977580-9e4f-11eb-970a-24c156d5dc1e.png)

(Though they still need a black outline, which isnt hard to add)

**Comment by Helliaca** [comment]
I haven't tried how they look when as small as in hoi4, but I reckon it would still be better. What are your thoughts?

**Comment by Helliaca** [comment]
Leather seems to be a bit more difficult to find. Maybe something like this could work?

![flare_armor](https://user-images.githubusercontent.com/18307020/114949844-2dedd400-9e52-11eb-87ac-9c02ae1ad049.png)

Also, maybe this one could work as mithril?
![mithril](https://user-images.githubusercontent.com/18307020/114950076-9c329680-9e52-11eb-9d0a-682875bee3a2.png)

^ I made that one for another hoi4 mod (one I never finished/released), so it should work fine.

**Comment by Ryless** [comment]
Those are fair comments. I had similar thoughts about some of them as well but those were the best I could find. Where did you find these ones? The Flax one specifically was hard to find, as expected, but really any plant icon would work. I was going to change the steel one as well since it didn't match the rest but wanted to get your thoughts first.

**Comment by Ryless** [comment]
I will say that the berry one probably wouldn't work since the symbol for gaining food is has green as well and would cover the red part and when you're losing food you would you wouldn't be able to see the red down arrows because the berry is also red.

**Comment by Helliaca** [comment]
I found those on [OpenGameArt](https://opengameart.org/), though resource-icons are fairly scarce, so I doubt you'll find much more there.

You might be able to find something on other sites like [shutterstock](https://www.shutterstock.com/search/game+resource+icon) or [dreamstime](https://www.dreamstime.com/illustration/game-resources-icons.html) but you should look at their licenses and getting a proper png usually requires a trial account or whatever,

Another option would be to look for public domain/cc0 cliparts like [here](https://publicdomainvectors.org/en/search/wood/1) or [here](https://openclipart.org/detail/20280/wood-icon).

Otherwise, you can of course always just google, though you would always have to check if we can use it. Funnily enough, I can recommend *Bing* for this :D, unlike Google, you can actually search for images with a certain license (like public domain). [Here](https://www.bing.com/images/search?q=wood%20icon&qs=n&form=QBIR&qft=%20filterui%3Alicense-L1&sp=-1&pq=wood%20ico&sc=5-8&cvid=78B78BEC58294BD0877666D9E10B98F1&first=1&tsc=ImageBasicHover) is an example.

**Comment by Ryless** [comment]
I think these are better overall for sure. 


![Hearts of Iron IV Screenshot 2021 04 15 - 20 37 30 72](https://user-images.githubusercontent.com/80797099/114959346-7beee180-9e2a-11eb-9395-74c684714ab9.png)

- Not 100% on the meat as food but it works and is likely the best we'll get since a lot of food will be red or green or both, wheat is going to probably be too detailed and bread looks like logs. 
- Mithril looks good, I didn't add a black border to it because it already had a light border that makes it look glowy
- For leather, I used something similar to what I had because it is a pretty common image of leather as a resource. For example, Minecraft uses something similar, and if you look up leather icons it's pretty much only images like that. I made it look better now tho. 
- I replaced flax with string for now because IDK what to do about that one.
- Redid the steel and wood ones even though the last ones were decent. These do look better for sure though.

What do you think about them now?

**Comment by Helliaca** [comment]
Yes, this definitely looks a lot better. I still think some of the icons are a little off. 

- The porkchop for food just looks a little strange, hard to pin down why.
- The leather icon seems to over-saturated.
- The string icon still looks bad, especially on dark backgrounds
- The steel icon seems to detailed for its tiny size. It might be better to use just one ingot as the symbol.
- I think the outline on the icons could be smoother.

I've experimented myself with this a bit. Here's a `resources_strip.dds` I've come up with:

![resources_strip_new](https://user-images.githubusercontent.com/18307020/115022029-17c92d80-9ebd-11eb-9ad5-81d214e429a8.png)

Convert it to dds and test it out, then let me know what you think. I think it is overall better still. I found the string/leather icons from a cc0 minecraft texturepack and the food icon is straight from Stellaris. I shifted the tone/saturation values somewhat to give each resource a more distinct color. I also applied a smooth dark outline to each.

**Comment by Helliaca** [comment]
For reference: this is what it looks like:
![image](https://user-images.githubusercontent.com/18307020/115022370-945c0c00-9ebd-11eb-8e49-ed1dfa31975b.png)

**Comment by Ryless** [comment]
These look good. Definitely  better than what I had. If you're good with these then so am I. The only ones that could be improved maybe is the food and string but idk how and these are sufficient for me. I'll do all the localisation stuff now after I finish the other icons That I need to do still.

**Comment by Ryless** [comment]
Here's my current status on this stuff:

Redo resource icons - 95% done (as far as I know I just have to do one alert icon)
Set resource localisation - 100% done
Food for every unit, always a little consumption. (On very low, seems to not make a difference but helps the food resource make sense)
Change equipment requirements - 100% done (Need to be checked for balance and stuff) 
Change equipment localisation/Change localisation for tech tree - 50% done
Balance resource locations 
Change Focus trees to make more sense with rework - 100% done
Change oil refineries to farms
     - Icons (tech icons)(building icons)
     - localisation - 95% done (Just a few descriptions left)
Create mithril equipment (Might not do for a little while)

So I'm getting there slowly, but it is hard to find a line to stop at necessarily. Especially since this is in part a tech rework as well lol. I think when I finish the localisation on everything that will be a deliverable first iteration because then the resource costs will at least make sense and the resources themselves should be done. That is the issue though because I do not know exactly what I should name some equipment. Right now I have the following:

infantry equipment -> Steel swords of different qualities
motorized/mechanized - Carriages
artillery - Bows (This could be split off into three different sections though that I was thinking of but I don't know if it would be smart to do so or not. At the very least I assume you'd be cool with rocket artillery being crossbows? (Bows, Crossbows, Javelins?))
Anti-Air - Nothing (Air as a whole is in an interesting spot obviously because of how middle earth is designed. Could add anti_air to bow equipment which would make sense but would be odd gameplay-wise.)
Anti-Tank - Pikes

Light tank - Light cavalry (Would have names for each country preferably) 
light-tank-recon - Scout Cavalry
Medium tank - Armored cavalry (Would have names for each country preferably (Gondorian Knights, Harad Kataphracts, Greater Wargs, etc.)(But I'm not going to do that right now.)
Heavy-tank - Catapult/Trebuchet ( Maybe have it split into two paths? both have heavy tankish stats but something about them is different?)
Modern-tank - (Trolls/Ents would be pretty powerful so maybe they'd have similar stats to modern tanks? Of course then have to move things around in the tech tree which is not too difficult.)
Super-heavy - Mumakil (harad only)
Doing it this way would allow everyone to get light, medium and heavy tanks, Mordor and Ents to get modern tanks (Could add decisions to ask Mordor for trolls or ents for ents and just unlock the tech like that too. Wouldn't be too hard to implement.) and super-heavy for Harad. 


Each tank (Light, Medium, Heavy, Super-heavy, and Modern) all have three variants as well which  I wanted to get your opinion on. Do you want to include those or not. If so here is what I was thinking each could be
Artillery tanks - Mounted Archers (Ents throwing rocks?)
Tank destroyer tanks - Lancers? (attack trolls?)
AA Tanks - ????

I'm leaving the ships and Air as-is for now but the resources for them have been changed.

This kind of stuff naturally leads to questions of making new tech trees for siege machines for example. Which is a later thing that we could do. 

Anyways my main questions are:
- Are you good with the names I have up there so far?
- What do you think about the variants of tanks?
- What do you think about three types of artillery? (Bows, Crossbows, Javelins?)
- If this is the tech route we're going down are we removing infantry cavalry?
- What do you think about tech reworks in the long run? (Siege tab, Name for artillery tab since it is more like different types of infantry equipment)

Again, my main goal for this is the resource reskin, but to make that actually make sense a lot of this stuff has to at least tentatively be decided for now.

**Comment by Ryless** [comment]
> Infantry equipment: I have no problem with steel swords, but I kinda prefer just "infantry equipment". Which is not at all wrong here either, even in a medieval setting.

I suppose Infantry equipment does make a little more sense because there is more than just swords around so I'll change that. 

>  Anti-Air: How about ballista ?

I considered ballista but wasn't sure about them. I forgot why I didn't do them in the first place so it probably wasn't that great of a reason. I like this and the "ground ballista" because that makes that whole section fit together nicely. I'll move pikes to the anti-tank infantry tech that branches off of the infantry equipment. That is likely a better place for them.

>Tanks: All your decisions regarding tanks are fine by me. I'm not a huge fan of making super heavys harad only, but ok.

Well, the other option that I thought of is having siege towers as super-heavy tanks? So let me know if you wanna do that instead and then mumakil will be a separate tech with trolls/ents. Works fine with me and will give the player more options so I assume you'd like it more? Definitely have to touch up these stats at some point to make these things feel like siege weapons instead of tanks though. 

As for the cavalry, We don't really have an option but to get rid of them if we want to adapt the tree. We'd either have to make a bunch of cavalry subunits and then make 5? different types of siege machines to fulfill all the tanks or do what we're doing here. The former option isn't necessarily a bad idea but it seems overly complicated and I don't think we would be able to make 5 different siege machines all have a role. 

Armoured cars could be turned into armoured carriages? IDK that seems to be the most similar thing to a car as it gets in medieval times. Like a roofed carriage.

For the future stuff, I'm just spitballing ideas that come up in my head. I believe that we should do stuff similar to this project and the map stuff, things that will make the mod feel more polished and fleshed out now, and then move on to things like the tech idea or working on the east. When it comes down to it tech would be at the very end of ideas I currently have I was just seeing if you felt strongly about it at all.

**Comment by Helliaca** [comment]
> I thought of is having siege towers as super-heavy tanks?

Works for me. Although I'm not *completely* opposed to turning SH tanks into mumakil either. I'll leave the decision up to you depending what you think works/fits best.

> As for the cavalry, We don't really have an option but to get rid of them if we want to adapt the tree.

Yeah, getting rid of the cavalry seems inescapable. I was just saying we should watch out as not to do this too much in future for other units as well.

**Comment by Helliaca** [comment]
The resources have been changed, the remaining hurdles are all tech-related. So I'm closing this down and opening [Tech Rework](https://github.com/Helliaca/HoI4-LotrMod/issues/12) instead.
